name: Gerar APK Local via Cordova
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixando seu codigo
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Instalar Cordova e Gerar APK
        run: |
          npm install -g cordova
          # Cria o projeto android internamente
          cordova create projeto com.jotap.sensivip SensiVIP
          cd projeto
          cordova platform add android
          # Copia o seu arquivo index.html (garanta que o nome está exato) para dentro do app
          cp ../index.html www/index.html
          # Compila o instalador
          cordova build android --no-telemetry

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: Sensi-VIP-Instalador
          path: projeto/platforms/android/app/build/outputs/apk/debug/*.apk